### ISSUE TITLE
Trained model is not working during inference.

### ISSUE THREAD

**Issue by aravind-h-v** [tencent-ailab/IP-Adapter#103]
I trained an ip adapter using the command:
`python3 tutorial_train.py --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5" --image_encoder_path="${HOME}/GITHUB/tencent-ailab/IP-Adapter/model_checkpoint/image_encoder" --data_json_file="${HOME}/DRESS_CODE/DressCode/all.json" --data_root_path="${HOME}/DRESS_CODE/DressCode/all" --mixed_precision="fp16" --resolution=512 --train_batch_size=12 --dataloader_num_workers=4 --learning_rate=1e-04 --weight_decay=0.01 --output_dir="${HOME}/DRESS_CODE/DressCode/out2" --save_steps=100`

and tried inference:

`
#!/usr/bin/python3
import torch
import os

from PIL import Image

from ip_adapter import (IPAdapterPlus, IPAdapter)

from diffusers import (StableDiffusionPipeline, StableDiffusionImg2ImgPipeline,
                       StableDiffusionInpaintPipelineLegacy, DDIMScheduler,
                       AutoencoderKL)

HOME = os.environ.get('HOME', '/root')
base_model_path = 'runwayml/stable-diffusion-v1-5'
vae_model_path = "stabilityai/sd-vae-ft-mse"
image_encoder_path = HOME + '/GITHUB/tencent-ailab/IP-Adapter/model_checkpoint/image_encoder'
ip_ckpt = '/home/ubuntu/DRESS_CODE/DressCode/out2/checkpoint-200/pytorch_model.bin'
device = "cuda"
path_image = '/home/ubuntu/GP_VTON_INFERENCE_DATA_ORIGINAL/cloth/1.png'

noise_scheduler = DDIMScheduler(num_train_timesteps=1000,
                                beta_start=0.00085,
                                beta_end=0.012,
                                beta_schedule='scaled_linear',
                                clip_sample=False,
                                set_alpha_to_one=False,
                                steps_offset=1)

pipe = StableDiffusionPipeline.from_pretrained(base_model_path,
                                               torch_dtype=torch.float16,
                                               scheduler=noise_scheduler,
                                               feature_extractor=None,
                                               safety_checker=None)

image = Image.open(path_image)
image.resize((256, 256))

ip_model = IPAdapter(pipe, image_encoder_path, ip_ckpt, device)

images = ip_model.generate(
    pil_image=image,
    num_samples=1,
    num_inference_steps=50,
    seed=1234,
    prompt="best quality, high quality, wearing a hat on the beach",
    scale=0.6)
`

but got an issue:

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[4], line 38
     35 image = Image.open(path_image)
     36 image.resize((256, 256))
---> 38 ip_model = IPAdapter(pipe, image_encoder_path, ip_ckpt, device)
     40 images = ip_model.generate(
     41     pil_image=image,
     42     num_samples=1,
   (...)
     45     prompt="best quality, high quality, wearing a hat on the beach",
     46     scale=0.6)

File ~/GITHUB/tencent-ailab/IP-Adapter/ip_adapter/ip_adapter.py:53, in IPAdapter.__init__(self, sd_pipe, image_encoder_path, ip_ckpt, device, num_tokens)
     50 # image proj model
     51 self.image_proj_model = self.init_proj()
---> 53 self.load_ip_adapter()

File ~/GITHUB/tencent-ailab/IP-Adapter/ip_adapter/ip_adapter.py:91, in IPAdapter.load_ip_adapter(self)
     89 def load_ip_adapter(self):
     90     state_dict = torch.load(self.ip_ckpt, map_location="cpu")
---> 91     self.image_proj_model.load_state_dict(state_dict["image_proj"])
     92     ip_layers = torch.nn.ModuleList(self.pipe.unet.attn_processors.values())
     93     ip_layers.load_state_dict(state_dict["ip_adapter"])

KeyError: 'image_proj'

Any idea what might be the issue?

**Comment by aravind-h-v** [comment]
I downloaded the image encoder inside the ip adapter repo by running:

`mkdir -pv -- 'model_checkpoint/image_encoder'
cd 'model_checkpoint/image_encoder'
aria2c -c -x16 -j16 'https://huggingface.co/h94/IP-Adapter/resolve/main/models/image_encoder/model.safetensors' '-o' 'model.safetensors'
aria2c -c -x16 -j16 'https://huggingface.co/h94/IP-Adapter/raw/main/models/image_encoder/config.json' '-o' 'config.json'`

**Comment by xiaohu2015** [comment]
@aravind-h-v https://github.com/tencent-ailab/IP-Adapter/issues/17#issuecomment-1696961596

**Comment by aravind-h-v** [comment]
ok thanks, that worked!
