### ISSUE TITLE
Shape mismatch between image and text encoder during training.

### ISSUE THREAD

**Issue by aravind-h-v** [tencent-ailab/IP-Adapter#107]
Tried training a normal (not plus) sdxl ip adapter with sdxl image encoder (https://huggingface.co/h94/IP-Adapter/resolve/main/sdxl_models/image_encoder/):

    python3 tutorial_train.py \
      '--pretrained_model_name_or_path=stabilityai/stable-diffusion-xl-base-1.0' \
      "--image_encoder_path=${HOME}/GITHUB/tencent-ailab/IP-Adapter/model_checkpoint/sdxl/image_encoder" \
      "--data_json_file=${HOME}/DRESS_CODE/DressCode/input.json" \
      "--data_root_path=${HOME}/DRESS_CODE/DressCode/input" \
      "--mixed_precision=fp16" \
      '--resolution=1024' \
      '--train_batch_size=2' \
      '--dataloader_num_workers=4' \
      '--learning_rate=1e-04' \
      '--weight_decay=0.01' \
      "--output_dir=${HOME}/DRESS_CODE/DressCode/out3" \
      '--save_steps=100' \
    ;

But got the error:

    Traceback (most recent call last):
      File "/home/ubuntu/GITHUB/tencent-ailab/IP-Adapter/tutorial_train.py", line 381, in <module>
        main()
      File "/home/ubuntu/GITHUB/tencent-ailab/IP-Adapter/tutorial_train.py", line 356, in main
        noise_pred = ip_adapter(noisy_latents, timesteps, encoder_hidden_states, image_embeds)
      File "/home/ubuntu/dbnew/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/home/ubuntu/dbnew/lib/python3.10/site-packages/accelerate/utils/operations.py", line 636, in forward
        return model_forward(*args, **kwargs)
      File "/home/ubuntu/dbnew/lib/python3.10/site-packages/accelerate/utils/operations.py", line 624, in __call__
        return convert_to_fp32(self.model_forward(*args, **kwargs))
      File "/home/ubuntu/dbnew/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
        return func(*args, **kwargs)
      File "/home/ubuntu/GITHUB/tencent-ailab/IP-Adapter/tutorial_train.py", line 115, in forward
        encoder_hidden_states = torch.cat([encoder_hidden_states, ip_tokens], dim=1)
    RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 768 but got size 2048 for tensor number 1 in the list.

But when I use the supplied model from https://huggingface.co/h94/IP-Adapter/resolve/main/sdxl_models/ip-adapter_sdxl.bin for inference with the above image encoder, the results work fine. How to fix the training issue (I want to train SDXL ip adapters on custom dataset)?

On a side note, I saw that when loading the IP adapters from a file:

    def load_ip_adapter(self):
        state_dict = torch.load(self.ip_ckpt, map_location="cpu")
        self.image_proj_model.load_state_dict(state_dict["image_proj"])
        ip_layers = torch.nn.ModuleList(self.pipe.unet.attn_processors.values())
        ip_layers.load_state_dict(state_dict["ip_adapter"])

the source file is in `IP-Adapter/ip_adapter/ip_adapter.py`, the modules ip_layers is never used. Is this intended ?

Thanks in advance!

**Comment by xiaohu2015** [comment]
@aravind-h-v 
1) for the training, it seems you use a wrong image encoder or base model?
2) the ip layers are inserted into the SD with set_attention_processor.   https://github.com/tencent-ailab/IP-Adapter/blob/c1515e906d2ded91812e2f55858c500aeb3a5d08/ip_adapter/ip_adapter.py#L81C26-L81C26

**Comment by aravind-h-v** [comment]
1. I was able to use the sdxl image encoder with sdxl base model and provided checkpoint to infer correctly, so I was a bit puzzled.
2. Thanks! Will check this.

**Comment by xiaohu2015** [comment]
> encoder_hidden_states

`encoder_hidden_states` should be 2048-dim, but from your error message, it is 768-dim

**Comment by xiaohu2015** [comment]
> `encoder_hidden_states` should be 2048-dim, but from your error message, it is 768-dim

encoder_hidden_states should be 2048-dim, but from your error message, it is 768-dim

**Comment by xiaohu2015** [comment]
> 1. I was able to use the sdxl image encoder with sdxl base model and provided checkpoint to infer correctly, so I was a bit puzzled.
> 2. Thanks! Will check this.

encoder_hidden_states should be 2048-dim, but from your error message, it is 768-dim

**Comment by aravind-h-v** [comment]
ya,, does this have something to do with text_encoder vs text_encoder_2 that is there with sdxl ?
Any idea on how to original SDXL ip adapters were trained ?

**Comment by xiaohu2015** [comment]
> python3 tutorial_train.py

I missed some things, you should use `python3 tutorial_train_sdxl.py`

**Comment by xiaohu2015** [comment]
> ya,, does this have something to do with text_encoder vs text_encoder_2 that is there with sdxl ? Any idea on how to original SDXL ip adapters were trained ?

I missed some things, you should use python3 tutorial_train_sdxl.py

**Comment by aravind-h-v** [comment]
oh this file was created yesterday! Thanks! I had also missed this.
