### ISSUE TITLE
TypeError: IPAdapterPlus.get_image_embeds() got an unexpected keyword argument 'clip_image_embeds'

### ISSUE THREAD

**Issue by whiterose199187** [tencent-ailab/IP-Adapter#130]
I'm trying the following. getting an error while generating images

base_model_path = "runwayml/stable-diffusion-v1-5"
vae_model_path = "stabilityai/sd-vae-ft-mse"
image_encoder_path = "/root/models/image_encoder"
ip_ckpt = "/root/models/ip-adapter-plus-face_sd15.bin"
device = "cuda"

noise_scheduler = DDIMScheduler(
    num_train_timesteps=1000,
    beta_start=0.00085,
    beta_end=0.012,
    beta_schedule="scaled_linear",
    clip_sample=False,
    set_alpha_to_one=False,
    steps_offset=1,
)

vae = AutoencoderKL.from_pretrained(vae_model_path).to(dtype=torch.float16)
pipe = StableDiffusionPipeline.from_pretrained(
    base_model_path,
    torch_dtype=torch.float16,
    scheduler=noise_scheduler,
    vae=vae,
    feature_extractor=None,
    safety_checker=None
)

image = Image.open("/root/face.png")
image.resize((256, 256))
ip_model = IPAdapterPlus(pipe, image_encoder_path, ip_ckpt, device, num_tokens=16)
images = ip_model.generate(pil_image=image, num_samples=4, num_inference_steps=50, seed=420,
            prompt="a beautiful girl in a garden")

`Traceback (most recent call last):
  File "/root/IP-Adapter/generate_images.py", line 56, in <module>
    images = ip_model.generate(pil_image=image, num_samples=4, num_inference_steps=50, seed=420,
  File "/root/IP-Adapter/ip_adapter/ip_adapter.py", line 156, in generate
    image_prompt_embeds, uncond_image_prompt_embeds = self.get_image_embeds(pil_image=pil_image, clip_image_embeds=clip_image_embeds)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
TypeError: IPAdapterPlus.get_image_embeds() got an unexpected keyword argument 'clip_image_embeds'`

Please advise on how to fix this? Thanks

**Comment by xiaohu2015** [comment]
@whiterose199187 please update the code, I fix the bug

**Comment by whiterose199187** [comment]
thanks for the quick fix!
