### ISSUE TITLE
AttributeError: 'StableDiffusionXLCustomPipeline' object has no attribute 'maybe_free_model_hooks

### ISSUE THREAD

**Issue by whiterose199187** [tencent-ailab/IP-Adapter#131]
I get this error while using `StableDiffusionXLCustomPipeline`

I just commented out https://github.com/tencent-ailab/IP-Adapter/blob/f40c80a19b23d5487707a5bcaf710f6dedafca75/ip_adapter/custom_pipelines.py#L400 for now to make it work

**Comment by xiaohu2015** [comment]
do you use the latest version of diffusers?

**Comment by bitcoinvsalts** [comment]
@xiaohu2015 the diffuser is not used in this example: https://github.com/tencent-ailab/IP-Adapter/blob/main/ip_adapter_sdxl_plus-face_demo.ipynb

**Comment by whiterose199187** [comment]
yes, i was on an older version

**Comment by bitcoinvsalts** [comment]
so what version of diffusers should I use?

**Comment by xiaohu2015** [comment]
> so what version of diffusers should I use?

use the latest version

**Comment by bitcoinvsalts** [comment]
but the diffuser is not used in your demo code. Could you correct the demo though?

**Comment by xiaohu2015** [comment]
> but the diffuser is not used in your demo code.

this file needs https://github.com/tencent-ailab/IP-Adapter/blob/main/ip_adapter/custom_pipelines.py

**Comment by bitcoinvsalts** [comment]
after updating the custom_pipelines.py with the new version, I am getting this new error:

` File "/home/ec2-user/reebok/apps/service-pump-engine/service_pump_engine/ip_adapter/custom_pipelines.py", line 279, in __call__
Nov 07 14:16:43 ip-172-31-14-127.us-west-1.compute.internal startup.sh[3715]:     add_time_ids = self._get_add_time_ids(
Nov 07 14:16:43 ip-172-31-14-127.us-west-1.compute.internal startup.sh[3715]: TypeError: _get_add_time_ids() got an unexpected keyword argument 'text_encoder_projection_dim'
`

**Comment by xiaohu2015** [comment]
> after updating the custom_pipelines.py with the new version, I am getting this new error:
> 
> `File "/home/ec2-user/reebok/apps/service-pump-engine/service_pump_engine/ip_adapter/custom_pipelines.py", line 279, in __call__ Nov 07 14:16:43 ip-172-31-14-127.us-west-1.compute.internal startup.sh[3715]: add_time_ids = self._get_add_time_ids( Nov 07 14:16:43 ip-172-31-14-127.us-west-1.compute.internal startup.sh[3715]: TypeError: _get_add_time_ids() got an unexpected keyword argument 'text_encoder_projection_dim'`

did you use the version 0.22.1, ?https://github.com/huggingface/diffusers/blob/v0.22.1/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py#L573

**Comment by bitcoinvsalts** [comment]
```
poetry show diffusers
 name         : diffusers                                      
 version      : 0.22.1                                         
 description  : State-of-the-art diffusion in PyTorch and JAX. 

dependencies
 - filelock *
 - huggingface-hub >=0.13.2
 - importlib-metadata *
 - numpy *
 - Pillow *
 - regex !=2019.12.17
 - requests *
 - safetensors >=0.3.1

```

**Comment by mingfuyan** [comment]
> after updating the custom_pipelines.py with the new version, I am getting this new error:
> 
> `File "/home/ec2-user/reebok/apps/service-pump-engine/service_pump_engine/ip_adapter/custom_pipelines.py", line 279, in __call__ Nov 07 14:16:43 ip-172-31-14-127.us-west-1.compute.internal startup.sh[3715]: add_time_ids = self._get_add_time_ids( Nov 07 14:16:43 ip-172-31-14-127.us-west-1.compute.internal startup.sh[3715]: TypeError: _get_add_time_ids() got an unexpected keyword argument 'text_encoder_projection_dim'`

@bitcoinvsalts   I had the same problem. Would you be so kind as to share some insights or steps you took to resolve this problem? Any guidance or advice you can provide would be immensely appreciated, and I believe it could also be beneficial to others who might encounter the same issue in the future.
