### ISSUE TITLE
Got very bad result with LCM-lora

### ISSUE THREAD

**Issue by blx0102** [tencent-ailab/IP-Adapter#144]
Hi! I tried to use IPAdapter with LCM-lora like below, code is borrowed from https://huggingface.co/latent-consistency/lcm-lora-sdv1-5:

```
model_id = "models/flat2DAnimerge"
adapter_id = "models/loras/pytorch_lora_weights.safetensors"
image_encoder_path = "./models/image_encoder"
ip_ckpt_plus_face = "./models/ip-adapter-plus-face_sd15.bin"

pipe = AutoPipelineForText2Image.from_pretrained(model_id, torch_dtype=torch.float16, variant="fp16", safety_checker=None)
pipe.scheduler = LCMScheduler.from_config(pipe.scheduler.config)
pipe.to("cuda")

# load and fuse lcm lora
pipe.load_lora_weights(adapter_id)
pipe.fuse_lora()
ip_model_plus = IPAdapterPlus(pipe, image_encoder_path, ip_ckpt_plus_face, "cuda", num_tokens=16)

prompt = "Self-portrait oil painting, a beautiful cyborg with golden hair, 8k"

# disable guidance_scale by passing 0
img = Image.open("face.png")
image = img.resize((256,256))image = ip_model_plus.generate(pil_image=image, num_inference_steps=4, prompt=prompt, scale=0.5)[0]
image.save("1.png") 
```

But the result is very bad:
![lcm](https://github.com/tencent-ailab/IP-Adapter/assets/17761044/5a9229ce-98cc-4c6b-a49a-9a415bab0eed)

Below is the result of text-to-image without IPAdapter when using LCM-lora:
![1](https://github.com/tencent-ailab/IP-Adapter/assets/17761044/bf446304-3562-40ee-98d1-9d8aaff20a94)

**Comment by xiaohu2015** [comment]
@blx0102 do you also tested ip-adapter-sd15?

**Comment by blx0102** [comment]
@xiaohu2015 Yes, I've tried ip-adapter_sd15, ip-adapter-plus_sd15, ip-adapter-plus-face_sd15, they all output image like above. Also, increasing infer steps didn't help.

**Comment by xiaohu2015** [comment]
it seems to work with LCM lora https://github.com/huggingface/diffusers/pull/5713, maybe I should do some tests

**Comment by blx0102** [comment]
@xiaohu2015 Thanks! I will upgrade my diffusers' version and try that code.

**Comment by maximepeabody** [comment]
Make sure your guidance scale is set to < 2.0 (works well with 1.0). if it's using the default 7.5 or 8, then it will lead to bad results

**Comment by blx0102** [comment]
> Make sure your guidance scale is set to < 2.0 (works well with 1.0). if it's using the default 7.5 or 8, then it will lead to bad results

@maximepeabody Yeah, that's the point! This perfectly solved this problem.
