### ISSUE TITLE
Request: Undo Function in IPAdapter to Maintain Pipeline Component Integrity

### ISSUE THREAD

**Issue by arlegotin** [tencent-ailab/IP-Adapter#148]
I'm using IPAdapter in a workflow with multiple pipelines, reusing components like UNet, TextEncoder and others for efficiency. 

However, IPAdapter permanently alters UNet, limiting its reuse:
```python
# Original UNet
my_pipeline.unet  

# After applying IPAdapter
ip_adapter = IPAdapter(my_pipeline, ...)
my_pipeline.unet  # Mutated UNet
```
Could an 'undo' method be added to IPAdapter to reverse these changes? This would allow the UNet to be restored for further use:
```python
ip_adapter.undo()
my_pipeline.unet  # Restored UNet
```
This feature would greatly enhance IPAdapter's utility in complex workflows.
Thank you.

**Comment by catwell** [comment]
Not sure if this helps but if you use [the Refiners version](https://github.com/tencent-ailab/IP-Adapter/issues/92) you can do it (with `.eject()`).
