### ISSUE TITLE
When using controlnet, will the image feature calculate cross-attention with controlnet? Or just do cross attention with Unet's backbone?

### ISSUE THREAD

**Issue by illrayy** [tencent-ailab/IP-Adapter#177]

**Comment by xiaohu2015** [comment]
I tested two, all works.

**Comment by illrayy** [comment]
Thanks for your quick reply! Can you share what the differences are between the two methods and why you chose the current one?

> I tested two, all works. In current code, it just do cross attention with Unet's backbone

**Comment by xiaohu2015** [comment]
> Thanks for your quick reply! Can you share what the differences are between the two methods and why you chose the current one?
> 
> > I tested two, all works. In current code, it just do cross attention with Unet's backbone

only very small difference
