### ISSUE TITLE
use dinov2 as the image encoder

### ISSUE THREAD

**Issue by chuck-ma** [tencent-ailab/IP-Adapter#179]
I encountered this requirement in my application scenario: I need to be able to realistically restore all the details of an object, even with a text prompt.

I would like to use DINOv2 instead of CLIP as the image encoder for the following reasons: Recently, I read the paper 'Animate Anyone,' where it was mentioned that the training objective of the CLIP image encoder is to match with text embeddings. As a result, it may produce abstract and macro features, neglecting many small details. Additionally, the embedding obtained from the CLIP image encoder might not be large enough, potentially overlooking many details.

I am planning to implement my idea based on your ipadapter-full implementation. I will use DINOV2 as the image encoder to generate the embedding (including the cls token and patch token). Then, I will use an MLP to extract features from the embedding.As for data preprocessing:  segment the object and remove background.

I saw on the issue https://github.com/tencent-ailab/IP-Adapter/issues/100 that using DINOV2 can cause text prompts to not work properly. I'm wondering if my implementation above would also have this problem, or if there are any other design flaws. Any help would be appreciated

**Comment by xiaohu2015** [comment]
https://github.com/tencent-ailab/IP-Adapter/issues/175
