### ISSUE TITLE
Size mismatch when loading ip-adapter-plus_sdxl checkpoint

### ISSUE THREAD

**Issue by sherrydoge** [tencent-ailab/IP-Adapter#181]
Thanks for your great work!
I am confused when I try to train ip-adapter-plus and load the checkpoint of **ip-adapter-plus_sdxl_vit-h.bin** in huggingface h94/IP-Adapter. The parameter size mismatches in _proj_in_, _proj_out_ and _layers_.
I found that in [tutorial_train_plus.py](https://github.com/tencent-ailab/IP-Adapter/blob/f71c943b7e1d3ffccae8e4f04b9adebac037e19f/tutorial_train_plus.py#L309C1-L309C1) you give several parameters including _dim_, _dim_head_, _heads_, which might causes this issue. I wonder the settings of resampler when you train **ip-adapter-plus_sdxl_vit-h.bin**, and I also want to know how you choose them.
Looking forward to your reply!

**Comment by xiaohu2015** [comment]
https://github.com/tencent-ailab/IP-Adapter/blob/main/ip_adapter/ip_adapter.py#L328

**Comment by sherrydoge** [comment]
Thank you! I also noticed that in [tutorial_train_plus.py](https://github.com/tencent-ailab/IP-Adapter/blob/f71c943b7e1d3ffccae8e4f04b9adebac037e19f/tutorial_train_plus.py#L309C1-L309C1) you choose _unet_cross_attn_dim_ as the dim of resampler. However, in **ip-adapter-plus_sdxl**, you use _dim=1280_, which equals to the image encoder projection dim. I wonder if there is any influence on this choice.

**Comment by xiaohu2015** [comment]
> Thank you! I also noticed that in [tutorial_train_plus.py](https://github.com/tencent-ailab/IP-Adapter/blob/f71c943b7e1d3ffccae8e4f04b9adebac037e19f/tutorial_train_plus.py#L309C1-L309C1) you choose _unet_cross_attn_dim_ as the dim of resampler. However, in **ip-adapter-plus_sdxl**, you use _dim=1280_, which equals to the image encoder projection dim. I wonder if there is any influence about this choice.

i just a bug, not a feature. but I think it don't affect the result much.
