### ISSUE TITLE
IP-Adapter not working after installing

### ISSUE THREAD

**Issue by MrSmith44** [tencent-ailab/IP-Adapter#195]
Hi i cant seem to get the IP-Adapter to work It's installed and even shows in my manager but I always get the error message when starting ComfyUI If anyone has a fix it would be much appreciated thank you.

![Screenshot 2023-12-23 215544](https://github.com/tencent-ailab/IP-Adapter/assets/153255920/9ba610bc-321d-40ff-ad46-8e43c41893f8)

![Screenshot 2023-12-23 215816](https://github.com/tencent-ailab/IP-Adapter/assets/153255920/cfb441f7-8f49-4032-b17b-681575a76e0c)

** Log path: C:\Users\Smith\Desktop\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.1 seconds: C:\Users\Smith\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 6140 MB, total RAM 16108 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4050 Laptop GPU : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
### ComfyUI Revision: 1851 [a252963f] | Released on '2023-12-23'
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
OpenPose Editor: Loaded
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
Import times for custom nodes:

   0.0 seconds: C:\Users\Smith\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Image-Selector
   0.0 seconds: C:\Users\Smith\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Logic
   0.0 seconds: C:\Users\Smith\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds: C:\Users\Smith\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: C:\Users\Smith\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OpenPose-Editor
   0.0 seconds: C:\Users\Smith\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: C:\Users\Smith\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.6 seconds: C:\Users\Smith\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

**Comment by xiaohu2015** [comment]
hi, can you give a issue in ComfyUI_IPAdapter_plus repo

**Comment by MrSmith44** [comment]
@xiaohu2015 sorry I'm in the wrong repo lol my apologies mate :D
