### ISSUE TITLE
How to train IP-Adapter-plus-face-SDXL?

### ISSUE THREAD

**Issue by YoucanBaby** [tencent-ailab/IP-Adapter#198]
Hi, 

I try to modify tutorial_train_sdxl.py to train IP-Adapter-plus-face-SDXL, but I always encounter some dimension mismatch problems. Can you please release the code for training IP-Adapter-plus-face-SDXL?

Regards

**Comment by xiaohu2015** [comment]
hi, you can refer to https://github.com/tencent-ailab/IP-Adapter/blob/main/tutorial_train_plus.py and https://github.com/tencent-ailab/IP-Adapter/blob/main/tutorial_train_sdxl.py

**Comment by xiaohu2015** [comment]
I need some time to update the code
