### ISSUE TITLE
We couldn't connect to 'https://huggingface.co'

### ISSUE THREAD

**Issue by gagbaghdas** [tencent-ailab/IP-Adapter#209]
Hey guys. I'm trying to run the training script , and it gives me the following error. 

```
OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like runwayml/stable-diffusion-v1-5/ is not the path to a directory containing a scheduler_config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.
```
Anyone have an idea what I'm doing wrong?

**Comment by gagbaghdas** [comment]
> maybe you can firstly download the model into local path

Hey @xiaohu2015 . Is the v1-5-pruned.ckpt ok ?I've just downloaded it

**Comment by xiaohu2015** [comment]
```
from diffusers import StableDiffusionPipeline
import torch

model_id = "runwayml/stable-diffusion-v1-5"
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
pipe.save_pretrained("local_path")
```

**Comment by rafstahelin** [comment]
> Hey guys. I'm trying to run the training script , and it gives me the following error. 
> 
> 
> 
> ```
> 
> OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like runwayml/stable-diffusion-v1-5/ is not the path to a directory containing a scheduler_config.json file.
> 
> Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.
> 
> ```
> 
> Anyone have an idea what I'm doing wrong?

What's the training for?

**Comment by gagbaghdas** [comment]
@rafstahelin please see [here](https://github.com/tencent-ailab/IP-Adapter/issues/187)
