### ISSUE TITLE
about FaceID-Plus

### ISSUE THREAD

**Issue by y1xuan0726** [tencent-ailab/IP-Adapter#212]
The display effect of FaceID-Plus is so great, will you release FaceID-Plus and FaceID-Plus-V2 train code?

**Comment by xiaohu2015** [comment]
you can modify the training code of https://github.com/tencent-ailab/IP-Adapter/blob/main/tutorial_train_faceid.py

**Comment by y1xuan0726** [comment]
ok, thank you!
