### ISSUE TITLE
Training vram memory usage?

### ISSUE THREAD

**Issue by crj1998** [tencent-ailab/IP-Adapter#216]
Thanks author for sharing this awasome answer, I have read all the issue about training and know that you use 32G 8v100-gpus, batch=8 to train, which means the 32GB vram is enough. Howere when i run [tutorial_train_faceid.py](https://github.com/tencent-ailab/IP-Adapter/blob/main/tutorial_train_faceid.py) with batch 8, it use almost double of 32 GB. So i wander is there something i miss?
I use
```
torch==2.0.0+cu118
diffusers==0.22.1
accelerate==0.23.0
```
![image](https://github.com/tencent-ailab/IP-Adapter/assets/28671582/8d790e5d-acd5-4d7c-9a82-7f161ca82006)

**Comment by Ted-developer** [comment]
I also have a similar issue. In multi-GPU training, there's a problem with the loss gradient updates. I have modified the parameters that the optimizer needs to update. However, the VRAM usage is indeed very high. I suspect that it might be necessary to enable enable_xformers_memory_efficient_attention, and perhaps add a dedicated XFormersAttnProcessor for the IP Adapter.

**Comment by xiaohu2015** [comment]
I used deepspeed to train. also you can use xformers or torch2.0 attention processor

**Comment by fengyang0317** [comment]
According to https://huggingface.co/docs/diffusers/optimization/torch2.0, memory-efficient attention is enabled by default in torch 2.0. Did you also turn on the offload_param and offload_optimizer to allow batch=8 in V100? Thanks.

**Comment by xiaohu2015** [comment]
I don't use offload_param and offload_optimizer
