### ISSUE TITLE
AttributeError: 'StableDiffusionPipeline' object has no attribute 'encode_prompt'

### ISSUE THREAD

**Issue by gebaltso** [tencent-ailab/IP-Adapter#231]
Hello I am facing the AttributeError: 'StableDiffusionPipeline' object has no attribute 'encode_prompt' . I upgraded the diffusers, what else can I do? Thanks in advance.
I get this error when I try to run the following from ip_adapter_demo.ipynb:

# generate image variations
images = ip_model.generate(pil_image=image, num_samples=4, num_inference_steps=50, seed=42)
grid = image_grid(images, 1, 4)
grid

**Comment by Euron-ZC** [comment]
Hello,may I know how did you solve this problem? Thx.

**Comment by gebaltso** [comment]
> Hello,may I know how did you solve this problem? Thx.

Hello, as far as I remember after upgrading the diffusers and restarted the terminal it was ok. But unfortunately it has been a long time since I used it so I' m not 100% if it was just that.
