### ISSUE TITLE
Minimum Resources to train ( fine tune ) 

### ISSUE THREAD

**Issue by gagbaghdas** [tencent-ailab/IP-Adapter#232]
Hey guys. I'm trying to fine tune the IP-Adapter on clothes dataset, I'm wondering any rough estimations for resources needed to train the model ? I red, that for the training of IP-Adapter you guys used a single machine with 8xA100 , so I'm wondering what is the minimum resources I'll need to train it ?

**Comment by xiaohu2015** [comment]
I used 8x V100, in fact, you can use other low-end cards because we are training an adapter

**Comment by gagbaghdas** [comment]
@xiaohu2015 thanks. So in case I'll use 1x A100 , what do you think approx what kind of duration it will take to make a single iteration ? And do you have any rough estimation on how much iterations will I need to achieve the desired result? Just from your experience. I'm trying to understand the approx cost of the training

**Comment by xiaohu2015** [comment]
batch size = 8x8, needs train about 200,000 steps to achieve the desired result

**Comment by gagbaghdas** [comment]
@xiaohu2015 I see, and could you please how much it took to train on  8xV100 ?

**Comment by xiaohu2015** [comment]
2-3 days. but for the released model, it trained about 1,000,000 steps, need 7-10 days.

**Comment by gagbaghdas** [comment]
Got it, thank you.
