### ISSUE TITLE
Any other versions of IP-adapter FaceID for SDXL

### ISSUE THREAD

**Issue by George0726** [tencent-ailab/IP-Adapter#236]
Hi author,
IP-adapter FaceID SDXL version is really impressive! I am wondering if you have plans to release other versions of SDXL-based FaceID IP-adapter, like **IP-Adapter-FaceID-Plus** and **IP-Adapter-FaceID-PlusV2** or even with other faceID extractors (i.e. StyleGAN FFHQ embeddings).

**Comment by xiaohu2015** [comment]
need some time
