### ISSUE TITLE
Installing this for automatic 111?

### ISSUE THREAD

**Issue by DarqueLilly** [tencent-ailab/IP-Adapter#24]
can this be installed locally to stable diffusion Automatic 111?

**Comment by xiaohu2015** [comment]
@DarqueLilly hi, you can follow this: https://github.com/Mikubill/sd-webui-controlnet/issues/1927

**Comment by xiaohu2015** [comment]
@DarqueLilly hi, the plugin for IP-Adapter on webui is still in development, now you can use https://github.com/laksjdjf/IPAdapter-ComfyUI

**Comment by xiaohu2015** [comment]
@DarqueLilly ip-adapter is available on webui, you can install the new version of sd-webui-controlnet.
