### ISSUE TITLE
Which CLIP model do you use?

### ISSUE THREAD

**Issue by haofanwang** [tencent-ailab/IP-Adapter#25]
I notice that you provide image encoder on your own space, is it different from the models released by openai?

**Comment by xiaohu2015** [comment]
@haofanwang hi, for IP-Adapter of SD 1.5, we use  [OpenCLIP-ViT-H-14](https://huggingface.co/laion/CLIP-ViT-H-14-laion2B-s32B-b79K). But for IP-Adapter of SD xl, we use [OpenCLIP-ViT-bigG-14](https://huggingface.co/laion/CLIP-ViT-bigG-14-laion2B-39B-b160k).

**Comment by Twinkle-ce** [comment]
It seems that the model in your 
own space is different from the one mentioned above. At least, the file size is different, which raises concerns about its integrity or compatibility.
