### ISSUE TITLE
IP-Adapter FaceID-Plus V2 SDXL - what CLIP Vision Encoder is used?

### ISSUE THREAD

**Issue by kovalexal** [tencent-ailab/IP-Adapter#265]
Hi @xiaohu2015!

Thank you and your team for the great approach!

I have two questions related to recently added models:

1) I've been to run your code for IP-Adapter FaceID+ V2 SDXL and from the code perspective it seems that during it's training there was used an image encoder for SD.

When I try to use [SDXL image encoder](https://huggingface.co/h94/IP-Adapter/tree/main/sdxl_models/image_encoder) and initialise `IPAdapterFaceIDPlusXL` with it, I get the following error during `perceiver_resampler` state dict loading:
```
RuntimeError: Error(s) in loading state_dict for ProjPlusModel:
	size mismatch for perceiver_resampler.proj_in.weight: copying a param with shape torch.Size([2048, 1280]) from checkpoint, the shape in current model is torch.Size([2048, 1664]).
```

However, when I use [SD image encoder](https://huggingface.co/h94/IP-Adapter/tree/main/models/image_encoder) with `IPAdapterFaceIDPlusXL` everything loads as expected. Could you please confirm that `IPAdapterFaceIDPlusXL` has been trained with SD image encoder instead of SDXL image encoder?

2) Also, it seems that the output results for SDXL with this approach look a bit strange in my case. I used the following input picture:

![kovalexal_aligned_face](https://github.com/tencent-ailab/IP-Adapter/assets/1431206/0db56f01-b47c-448c-a5d7-2ef8469e007a)

And I get the following results as output:

![img0](https://github.com/tencent-ailab/IP-Adapter/assets/1431206/b0da11b4-2b4d-4d94-84a6-96fc9dbcd265)

Do you have any idea why this might be happening? I can provide the code to reproduce this problem if you wish.

**Comment by xiaohu2015** [comment]
show you inference code？

**Comment by Syndulla** [comment]
I am having a similar issue when trying to use P-Adapter FaceID-Plus V2 SDXL. Can anyone assist?

**Comment by xiaohu2015** [comment]
> I am having a similar issue when trying to use P-Adapter FaceID-Plus V2 SDXL. Can anyone assist?
> 
> ![image](https://private-user-images.githubusercontent.com/122099087/298279243-5dd379fd-fb5f-43b0-a0b3-ecd0cd5b296a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NTA5NjEsIm5iZiI6MTcwNTc1MDY2MSwicGF0aCI6Ii8xMjIwOTkwODcvMjk4Mjc5MjQzLTVkZDM3OWZkLWZiNWYtNDNiMC1hMGIzLWVjZDBjZDViMjk2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMFQxMTM3NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZTE1ZmY5NTkxZmIzM2U5MzYzNDFlNjkyOTQzNzYwYzRjNDk3MGFmNDVhNzZjYzBjNDdmYmNhNmU0ZjY3NjllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.34-UI__PhonAHKU4lM_dqVkic94imA__8240ko3yiB8)
> 
> This is what I am trying without success.

can you give a issue at https://github.com/cubiq/ComfyUI_IPAdapter_plus/

**Comment by kovalexal** [comment]
@xiaohu2015 here is the code for both issues:

1. SDXL Vision Encoder:

```python
import cv2
from insightface.app import FaceAnalysis
from insightface.utils import face_align
import torch

app = FaceAnalysis(name="buffalo_l", providers=['CUDAExecutionProvider', 'CPUExecutionProvider'])
app.prepare(ctx_id=0, det_size=(640, 640))

image = cv2.imread("/workspaces/IP-Adapter/notebooks/face.jpg")
faces = app.get(image)

faceid_embeds = torch.from_numpy(faces[0].normed_embedding).unsqueeze(0)
face_image = face_align.norm_crop(image, landmark=faces[0].kps, image_size=224) # you can also segment the face


import os, sys
import torch
from diffusers import StableDiffusionXLPipeline, DDIMScheduler, AutoencoderKL
from PIL import Image


from ip_adapter.ip_adapter_faceid_separate import IPAdapterFaceIDPlusXL
from ip_adapter.custom_pipelines import StableDiffusionXLCustomPipeline


base_model_path = "/mnt/DATA/checkpoints/civitai/sdxl/realvisxlV30Turbo_v30Bakedvae.safetensors"
image_encoder_path = "/mnt/DATA/checkpoints/huggingface/IP-Adapter/sdxl_models/image_encoder"
ip_ckpt = "/workspaces/IP-Adapter/checkpoints/ip-adapter-faceid-plusv2_sdxl.bin"
device = "cuda:2"


pipe = StableDiffusionXLPipeline.from_single_file(
    base_model_path,
    torch_dtype=torch.float16,
    feature_extractor=None,
    safety_checker=None
).to(device)


lora_ckpt = "/workspaces/IP-Adapter/checkpoints/ip-adapter-faceid-plusv2_sdxl_lora.safetensors"
pipe.load_lora_weights(lora_ckpt)
pipe.fuse_lora()


ip_model = IPAdapterFaceIDPlusXL(pipe, image_encoder_path, ip_ckpt, device)
```

```
RuntimeError: Error(s) in loading state_dict for ProjPlusModel:
	size mismatch for perceiver_resampler.proj_in.weight: copying a param with shape torch.Size([2048, 1280]) from checkpoint, the shape in current model is torch.Size([2048, 1664]).
```

However, when I change
```python
image_encoder_path = "/mnt/DATA/checkpoints/huggingface/IP-Adapter/sdxl_models/image_encoder"
```

to

```python
image_encoder_path = "/mnt/DATA/checkpoints/huggingface/IP-Adapter/models/image_encoder"
```

everything runs without an error. So, for me it seems that for SDXL there is used an SD Vision Encoder. Am I right? Is it expected, or there is some sort of error?

2. Output quality:

```python
import cv2
from insightface.app import FaceAnalysis
from insightface.utils import face_align
import torch

app = FaceAnalysis(name="buffalo_l", providers=['CUDAExecutionProvider', 'CPUExecutionProvider'])
app.prepare(ctx_id=0, det_size=(640, 640))

image = cv2.imread("/workspaces/IP-Adapter/notebooks/face.jpg")
faces = app.get(image)

faceid_embeds = torch.from_numpy(faces[0].normed_embedding).unsqueeze(0)
face_image = face_align.norm_crop(image, landmark=faces[0].kps, image_size=224) # you can also segment the face


import os, sys
import torch
from diffusers import StableDiffusionXLPipeline, DDIMScheduler, AutoencoderKL
from PIL import Image


from ip_adapter.ip_adapter_faceid_separate import IPAdapterFaceIDPlusXL
from ip_adapter.custom_pipelines import StableDiffusionXLCustomPipeline


base_model_path = "/mnt/DATA/checkpoints/civitai/sdxl/realvisxlV30Turbo_v30Bakedvae.safetensors"
image_encoder_path = "/mnt/DATA/checkpoints/huggingface/IP-Adapter/models/image_encoder"
ip_ckpt = "/workspaces/IP-Adapter/checkpoints/ip-adapter-faceid-plusv2_sdxl.bin"
device = "cuda:2"


pipe = StableDiffusionXLPipeline.from_single_file(
    base_model_path,
    torch_dtype=torch.float16,
    feature_extractor=None,
    safety_checker=None
).to(device)


lora_ckpt = "/workspaces/IP-Adapter/checkpoints/ip-adapter-faceid-plusv2_sdxl_lora.safetensors"
pipe.load_lora_weights(lora_ckpt)
pipe.fuse_lora()


ip_model = IPAdapterFaceIDPlusXL(pipe, image_encoder_path, ip_ckpt, device)


v2 = True
prompt = "photo of a smiling male in a business suite"
negative_prompt = "monochrome, lowres, bad anatomy, worst quality, low quality, blurry"

images = ip_model.generate(
     prompt=prompt, negative_prompt=negative_prompt, face_image=face_image, faceid_embeds=faceid_embeds, shortcut=v2, s_scale=1.0,
     num_samples=2, width=512, height=768, num_inference_steps=30, seed=2023,
     denoising_end=1.0
)
```

For base model I used [this](https://civitai.com/models/139562?modelVersionId=268861). Without IP-adapter it seems to work fine.

**Comment by Arcitec** [comment]
@kovalexal You've become confused by the bad file organization/names in Tencent's repository.

There is **no such thing as "SDXL Vision Encoder" vs "SD Vision Encoder".**

Those files are ViT (Vision Transformers), which are computer vision models that convert an image into a grid and then do object identification on each grid piece. It's used for things like automatic image text classification, object segmentation, etc.

It has literally 0% to do with Stable Diffusion at all.

There are two ViTs used by IP-Adapter:

- OpenCLIP ViT-H/14: 632.08M image parameters.
- OpenCLIP ViT-g/14: 1844.9M image parameters. It's [only 0.5-2% percentage points more accurate](https://laion.ai/blog/giant-openclip/) for almost 3x as much work.

Tencent have placed Vit-H in the "sd" folder and "Vit-g" in the "sdxl" folder. But that's not right. Almost every model, even for SDXL, was trained with the Vit-H encodings. Which makes sense since ViT-g isn't really worth using.

**Comment by Arcitec** [comment]
@xiaohu2015 Hello sir. :)

Could I please ask you one thing that I've always been wondering about your ViT models?

**CLIP-ViT-H-14-laion2B-s32B-b79K:**

- Official Repository: 3.94 GB at https://huggingface.co/laion/CLIP-ViT-H-14-laion2B-s32B-b79K/tree/main
- Your Repository: 2.53 GB at https://huggingface.co/h94/IP-Adapter/tree/main/models/image_encoder

**CLIP-ViT-bigG-14-laion2B-39B-b160k:**

- Official Repository: 10.2 GB at https://huggingface.co/laion/CLIP-ViT-bigG-14-laion2B-39B-b160k/tree/main
- Your Repository: 3.69 GB at https://huggingface.co/h94/IP-Adapter/tree/main/sdxl_models/image_encoder

Why the file size differences?

My guess: Maybe you took the official files and somehow erased the "image classification to text labels" part of the neural network? Otherwise I have no idea how you got the filesize so small, if it's really the same ViT models.

**Comment by xiaohu2015** [comment]
> @xiaohu2015 Hello sir. :)
> 
> Could I please ask you one thing that I've always been wondering about your ViT models?
> 
> **CLIP-ViT-H-14-laion2B-s32B-b79K:**
> 
> * Official Repository: 3.94 GB at https://huggingface.co/laion/CLIP-ViT-H-14-laion2B-s32B-b79K/tree/main
> * Your Repository: 2.53 GB at https://huggingface.co/h94/IP-Adapter/tree/main/models/image_encoder
> 
> **CLIP-ViT-bigG-14-laion2B-39B-b160k:**
> 
> * Official Repository: 10.2 GB at https://huggingface.co/laion/CLIP-ViT-bigG-14-laion2B-39B-b160k/tree/main
> * Your Repository: 3.69 GB at https://huggingface.co/h94/IP-Adapter/tree/main/sdxl_models/image_encoder
> 
> 1. Why the file size differences?
> 
> My guess: Maybe you took the official files and somehow erased the "image classification to text labels" part of the neural network? And only kept the vision encoding to numeric vectors part? Otherwise I have no idea how you got the filesize so small, if it's really the same ViT models.
> 
> 2. Do the bigger files (the official `laion` ViTs) work with IP-Adapter? I only use your smaller variants, since I want to be sure I use the same ViT that you trained your model with. But I am still curious. :)

only of  vision image encoder

**Comment by Arcitec** [comment]
> only of vision image encoder

Thank you sir that's what I was guessing. :)

So you basically removed the "vision to text" part of the ViT files.

And do the original, bigger laion ViT files work with IP-Adapter? Or should I always use your smaller versions?

**Comment by juefeix** [comment]
@kovalexal Hi there, were you able to get the image quality back to normal? I was also experience low quality (face identity lost, image of low visual appealingness) when trying `IPA-FaceID-Plus-V2-SDXL`, with various base models and encoders. 

eg:
- base_model_path = "SG161222/RealVisXL_V4.0"
- image_encoder_path = "laion/CLIP-ViT-H-14-laion2B-s32B-b79K"

See example here: 

![test_IPA-FaceID-Plus-V2-SDXL____a-person-in-front-of-Times-Square-NYC____1__2024_03_12_11_42_26__gen](https://github.com/tencent-ailab/IP-Adapter/assets/7005231/0114a2bc-a611-4468-a751-ca9ca6b13e77)

**Comment by garychan22** [comment]
@juefeix hi, have you solved this problem?

**Comment by garychan22** [comment]
@kovalexal hi, I am facing the problem of generating weird images using IPAdapterFaceIDPlusXL, how to solve this issue? I am using the image_encoder ``laion--CLIP-ViT-H-14-laion2B-s32B-b79K'' and ``ip-adapter-faceid-plusv2_sdxl.bin'' without loading the lora weights ``ip-adapter-faceid-plusv2_sdxl_lora.safetensors''.

**Comment by Arcitec** [comment]
For everyone posting about getting bad results, try reading the thread you're writing in. I already answered earlier why there's bad results and how to fix it:

https://github.com/tencent-ailab/IP-Adapter/issues/265#issuecomment-1904171966

**Comment by silence-tang** [comment]
> @kovalexal hi, I am facing the problem of generating weird images using IPAdapterFaceIDPlusXL, how to solve this issue? I am using the image_encoder `laion--CLIP-ViT-H-14-laion2B-s32B-b79K'' and `ip-adapter-faceid-plusv2_sdxl.bin'' without loading the lora weights ``ip-adapter-faceid-plusv2_sdxl_lora.safetensors''.

Hi, did you solve this problem?
