### ISSUE TITLE
What is the meaning of "Portrait photos"

### ISSUE THREAD

**Issue by fortunechen** [tencent-ailab/IP-Adapter#268]
Hi authors, 

I wonder why "Portrait photos" is easier to learn? 
<img width="1014" alt="image" src="https://github.com/tencent-ailab/IP-Adapter/assets/26025440/414a2d7b-cf8d-4f4e-bd7c-676c1eaaf446">

**Comment by xiaohu2015** [comment]
Images with a relatively large proportion of human faces, such as headshots
