### ISSUE TITLE
Purpose of Adapter Modules in training?

### ISSUE THREAD

**Issue by Bilal143260** [tencent-ailab/IP-Adapter#274]
The class `IPAdapter` takes in `image_proj_model` and `adapter_modules` along with some other params in it's constructor. `image_proj_model` is used in forward method and returns ip_tokens which are then concatenated with text-embeddings and passed to unet. However, I don't seee `adapter_modules` being used in forward method yet it is passed to optimizer. Can you clarify what's the difference between two and why do we even need `adapter_modules` if we are not even passing it to unet?

**Comment by xiaohu2015** [comment]
hi,  used in attention processor
