### ISSUE TITLE
sdxl-plusv2 seems not perform well 

### ISSUE THREAD

**Issue by Weifeng-Chen** [tencent-ailab/IP-Adapter#277]
I've test this version and found its performance is worse.  is there any prompts to replicate the results? 
here's my prompts: [
        'Manga drawing of a man', 
        'Funko Pop of a man', 
        'a man with sunglasses and a corgi',
        'a man in Ghibli anime style', 
        'a man making latte art', 
    ] and I get: 
![sdxl_male_0 jpg_as1 0_ss1 0_gs6_0 268](https://github.com/tencent-ailab/IP-Adapter/assets/34848350/54f671ac-7f9b-4c7e-9e2b-dbc5be886fab)

**Comment by Weifeng-Chen** [comment]
am I write a wrong code for inference? I modify the sd15 version so I'm not very sure..

**Comment by xiaohu2015** [comment]
do you also try comfyui?

**Comment by Weifeng-Chen** [comment]
> do you also try comfyui?

I forget the shortcut when I write the pipeline. sorry for your time.
