### ISSUE TITLE
ip-adapter faceID portrait cannot generate reliable 1024 * 1024 images

### ISSUE THREAD

**Issue by hnhparitosh** [tencent-ailab/IP-Adapter#279]
I recently tried the ip-adapter faceID portrait model just like the example shared on the hugging face. 
The 512 * 512 or 768 * 768 images are great but when the resolution is 1024 * 1024, it generates very bad anatomy like two identical heads growing out of a single body, etc. 
Please look at the image given below.
![portraut_out](https://github.com/tencent-ailab/IP-Adapter/assets/36197416/12e2600a-4421-4153-80db-6f68209b2cd0)

How can we avoid generating such outputs in 1024-resolution and can someone please share more information about this particular model?
Thank you.

**Comment by hnhparitosh** [comment]
Is there any way to use the high-resolution fix programmatically as I am not using UIs like automatic111 or comfyUI?

**Comment by xiaohu2015** [comment]
a simple way is firstly generate 512x512 images, then use a SR model to upscale to 1024x1024, and using image to image pipeline
