### ISSUE TITLE
Original dataset

### ISSUE THREAD

**Issue by thepowerfuldeez** [tencent-ailab/IP-Adapter#28]
Hi! Thank you for amazing work! It works like a charm!
I wonder which dataset you've used during training? Can you share more info about it? You specified in the paper that this is subset of LAION & COYO datasets. Maybe you have parameters that you've used for filtering such data? Aesthetic score threshold, p_unsafe / p_watermark, image size? And the proportion of LAION and COYO in your data
Do you think results will be different when trained on smaller dataset, let's say 1M samples? Do you think results would improve if used full resolution using variable aspect ratio bucketing instead of center crop?

**Comment by xiaohu2015** [comment]
@thepowerfuldeez hi, we use a subset of LAION and COYO: the image size are above 1024x1024, and Aesthetic score are above 5.  As we observe, using only 1M images also get good results. During our experiment, we center crop image to 512x512, where objects can be cropped, so using variable aspect ratio bucketing maybe improve result (you can firstly train with 512x512, then finetune it using variable aspect ratio bucketing).

**Comment by thepowerfuldeez** [comment]
Thank you! Why have you used image size above 1024 if using center crop 512? This is resizes to 512 on smaller side and center crops, isnt it?

**Comment by xiaohu2015** [comment]
@thepowerfuldeez 1) 1024x1024+ images are often high quality; 2) during training, we resizes to 512 on smaller side and center crops.

**Comment by thepowerfuldeez** [comment]
Gotcha! Thank you for your fast answer!
