### ISSUE TITLE
Just saying thanks

### ISSUE THREAD

**Issue by OmerMachluf** [tencent-ailab/IP-Adapter#3]
Awesome work! Thanks for your contribution

**Comment by hirowa** [comment]
Same here, is there any plans to make it available as an Automatic1111 plugin?

**Comment by xiaohu2015** [comment]
@hirowa There is already a plugin of ComfyUI: https://github.com/laksjdjf/IPAdapter-ComfyUI. For Automatic1111, you can follow this: https://github.com/Mikubill/sd-webui-controlnet/issues/1927

**Comment by hirowa** [comment]
Awesome, thank you!

> @hirowa There is already a plugin of ComfyUI: https://github.com/laksjdjf/IPAdapter-ComfyUI. For Automatic1111, you can follow this: [Mikubill/sd-webui-controlnet#1927](https://github.com/Mikubill/sd-webui-controlnet/issues/1927)
