### ISSUE TITLE
Unclear License

### ISSUE THREAD

**Issue by IICommitII** [tencent-ailab/IP-Adapter#310]
I wanted to ask if commercial use is allowed for this code. It seems that the license on GitHub indeed allows commercial usage. But the HuggingFace (https://huggingface.co/h94/IP-Adapter-FaceID) clearly mentions it's not allowed for commercial usage. So which one is it? It would greatly help if anyone can clarify this.

**Comment by ynie** [comment]
face id use insight face weight so it's not allow for commercial use

**Comment by xiaohu2015** [comment]
> I wanted to ask if commercial use is allowed for this code. It seems that the license on GitHub indeed allows commercial usage. But the HuggingFace (https://huggingface.co/h94/IP-Adapter-FaceID) clearly mentions it's not allowed for commercial usage. So which one is it? It would greatly help if anyone can clarify this.

code is allowed for  commercial use, but IP-Adapter-FaceID model is not allowed since  insight face weight is not allowed for commercial use.
hence, you can train your commercial model
