### ISSUE TITLE
Question about IP-Adapter FaceID plus

### ISSUE THREAD

**Issue by vim-hjk** [tencent-ailab/IP-Adapter#326]
Hello, I have a few questions.
Are LoRAs corresponding to ["ip_adapter"] in ip-adapter-faceid-plusv2_sd15.bin and LoRAs corresponding to ip-adapter-faceid-plusv2_sd15_lora.safetensors different LoRAs? 

When I check the weight tensor value, it looks different. 
If it is different, can I know how to apply LoRAs corresponding to ip-adapter-faceid-plusv2_sd15_lora.safetensors during training?

Thank you.

**Comment by xiaohu2015** [comment]
it should be same, the ip-adapter-faceid-plusv2_sd15_lora.safetensors is converted from ip-adapter-faceid-plusv2_sd15.bin
