### ISSUE TITLE
Question about training IP-Adapter-FaceID-PlusV2

### ISSUE THREAD

**Issue by vim-hjk** [tencent-ailab/IP-Adapter#328]
https://github.com/tencent-ailab/IP-Adapter/wiki/IP%E2%80%90Adapter%E2%80%90Face

According to the link above, it is important to crop the face image at different ratio of the face image, such as full body or upper body, for training. However, the example code is exactly the cropping method aligned around the face(InsightFace norm_crop).

My question is, ID embeddings are obtained using InsightFace norm_crop method on face images, and do you feed face images crop at various ratios in actual IP-Adapter training?

**Comment by masaisai111** [comment]
Where did you read about this training, and why is it not visible on the author's github

**Comment by xiaohu2015** [comment]
> https://github.com/tencent-ailab/IP-Adapter/wiki/IP%E2%80%90Adapter%E2%80%90Face
> 
> According to the link above, it is important to crop the face image at different ratio of the face image, such as full body or upper body, for training. However, the example code is exactly the cropping method aligned around the face(InsightFace norm_crop).
> 
> My question is, ID embeddings are obtained using InsightFace norm_crop method on face images, and do you feed face images crop at various ratios in actual IP-Adapter training?

hi，ID embeddings is precalculated offline (using InsightFace norm_crop method on face images)

**Comment by vim-hjk** [comment]
> Where did you read about this training, and why is it not visible on the author's github

You can find it on the Wiki tab of this repository.

**Comment by vim-hjk** [comment]
> > https://github.com/tencent-ailab/IP-Adapter/wiki/IP%E2%80%90Adapter%E2%80%90Face
> > According to the link above, it is important to crop the face image at different ratio of the face image, such as full body or upper body, for training. However, the example code is exactly the cropping method aligned around the face(InsightFace norm_crop).
> > My question is, ID embeddings are obtained using InsightFace norm_crop method on face images, and do you feed face images crop at various ratios in actual IP-Adapter training?
> 
> hi，ID embeddings is precalculated offline (using InsightFace norm_crop method on face images)

Thank you!
