### ISSUE TITLE
How to fine-tune IP-Adapter model with xformer?

### ISSUE THREAD

**Issue by seungyonglee0802** [tencent-ailab/IP-Adapter#329]
I got error message like below when I ran `unet.enable_xformers_memory_efficient_attention()`

`You are removing possibly trained weights of IPAttnProcessor2_0 with <diffusers.models.attention_processor.XFormersAttnProcessor object at 0x7fd027803940>`

Thanks in advance :)

**Comment by LeonJoe13** [comment]
I got the same problem, did you fix? many thanks

**Comment by JWargrave** [comment]
I have found the [answer](https://github.com/InstantID/InstantID/blob/04211a13703aacb6992e83ea9545be53616a2468/ip_adapter/attention_processor.py#L90)

**Comment by MontaEllis** [comment]
The core of the error is that you called `unet.enable_xformers_memory_efficient_attention()` after `unet.set_attn_processor(xxx)`. Simply switch the order.
