### ISSUE TITLE
Images from base model getting ruined if I load IP_Adapter

### ISSUE THREAD

**Issue by debjit-bw** [tencent-ailab/IP-Adapter#33]
```python
base_model_path = "yiffymix16_32"
image_encoder_path = "models/image_encoder/"
ip_ckpt = "models/ip-adapter_sd15.bin"
device = "cuda"

controlnet = ControlNetModel.from_pretrained("lllyasviel/sd-controlnet-openpose", torch_dtype=torch.float16)
pipe = StableDiffusionControlNetPipeline.from_pretrained("yiffymix16_32", safety_checker=None, controlnet=controlnet, torch_dtype=torch.float16)

# the below line is causing issues
ip_model = IPAdapter(pipe, image_encoder_path, ip_ckpt, device)

pipe = pipe.to("cuda")
pipe.scheduler = UniPCMultistepScheduler.from_config(pipe.scheduler.config)
pipe.enable_model_cpu_offload()
```

I have this above code. Now when i run the `pipe()` independently (without IPAdapter, for example `image = pipe(...)`), it produces hazy, unnatural images like this:
![weird](https://github.com/tencent-ailab/IP-Adapter/assets/68442560/4729aeca-96d3-4c9e-a9ed-52f1d5d77d9c)

But if I comment out the line `ip_model = IPAdapter(pipe, image_encoder_path, ip_ckpt, device)`, the pipe.() gives proper results. any idea why?

**Comment by xiaohu2015** [comment]
@debjit-bw hi,  it is beacuse we changed the `attention processor` of original `unet`. If your want to use original pipe, you can just set `scale=0`:
```
ip_model.set_scale(0)
```

**Comment by debjit-bw** [comment]
oh wow, thanks a lot!
