### ISSUE TITLE
person's skin is blue

### ISSUE THREAD

**Issue by guoti777** [tencent-ailab/IP-Adapter#368]
![IP-Adapter-FaceID](https://github.com/tencent-ailab/IP-Adapter/assets/97492481/0a3254de-b1ac-4cbb-a4bf-5bf3f452caf7)
ip-adapter-faceid; base model: Realistic_Vision_V4.0_noVAE; vae: sd-vae-ft-mse; 1M images, 10w iters.

**Comment by aycaecemgul** [comment]
please add a reproducible code, probably there is a mistake about rgb conversion?

**Comment by guoti777** [comment]
> please add a reproducible code, probably there is a mistake about rgb conversion?

thanks! Here is the transform code:
1. image:
```
        self.transform = transforms.Compose([
            transforms.Resize(self.size, interpolation=transforms.InterpolationMode.BILINEAR),
            transforms.CenterCrop(self.size),
            transforms.ToTensor(),
            # transforms.Normalize([-1], [1]),
            transforms.Normalize([0.5], [0.5]),
            # transforms.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5]),
        ])
        raw_image = Image.open(os.path.join(self.image_root_path, image_file))
        image = self.transform(raw_image.convert("RGB"))
```
2: faceid_embeds:
```
                image = cv2.imread(img_path)
                faces = app.get(image)
                if len(faces) == 1:
                    faceid_embeds = torch.from_numpy(faces[0].normed_embedding).unsqueeze(0)
                    torch.save(faceid_embeds, bin_path)
```
3. encode:
```
    images = torch.stack([example["image"] for example in data])
    face_id_embed = torch.stack([example["face_id_embed"] for example in data])
                    latents = vae.encode(batch["images"].to(accelerator.device, dtype=weight_dtype)).latent_dist.sample()
                    latents = latents * vae.config.scaling_factor
                image_embeds = batch["face_id_embed"].to(accelerator.device, dtype=weight_dtype)
                with torch.no_grad():
                    encoder_hidden_states = text_encoder(batch["text_input_ids"].to(accelerator.device))[0]
                noise_pred = ip_adapter(noisy_latents, timesteps, encoder_hidden_states, image_embeds)
```

**Comment by alexblattner** [comment]
it has to do with the convertion between cv2 and PIL. the color mapping is different

**Comment by guoti777** [comment]
> it has to do with the convertion between cv2 and PIL. the color mapping is different
raw_image is converted to RGB, do you mean "image = cv2.imread(img_path)" shoule add "image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)" when get faceid_embeds?

**Comment by guoti777** [comment]
> it has to do with the convertion between cv2 and PIL. the color mapping is different

raw_image is converted to RGB, do you mean "image = cv2.imread(img_path)" shoule add "image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)" when get faceid_embeds?
