### ISSUE TITLE
About version of ClipVisionModel

### ISSUE THREAD

**Issue by Foolbee** [tencent-ailab/IP-Adapter#371]
Thanks for your excellent work! I have noticed that you only trained the adapter module with CLIP-H-14 instead of CLIP-L-14. Are there any reasons for you to select the more complicated one but not the simpler one？Or you have tried the simpler one but got a worse result？

**Comment by xiaohu2015** [comment]
I find CLIP-H-14 is a little better than  CLIP-L-14

**Comment by Foolbee** [comment]
Thanks! I am wondering if the weights file of the pretrained adapter model with openai/clip-vit-l-14 as image encoder is available now, since it will be of great benefit to my work.

**Comment by xiaohu2015** [comment]
not available

**Comment by Foolbee** [comment]
Got it. Thanks for your reply!
