### ISSUE TITLE
have no 'pytorch_model.bin' been saved during training

### ISSUE THREAD

**Issue by xiaowu-1998** [tencent-ailab/IP-Adapter#375]

**Comment by xiaowu-1998** [comment]
when training is completed, there is no pytorch_model.bin left, and model.safetensors had only saved unet weights , so it occurs error during loading.
what can I do for save image_proj and adapter_modules successfully? or loading successfully. Thanks

**Comment by lucDoom** [comment]
any solution to this problem?
same issue looking for help

**Comment by ArmandXiao** [comment]
> any solution to this problem? same issue looking for help

```
import torch
import os
from safetensors.torch import load_file
ckpt = "output/checkpoint-50000/model.safetensors"
sd = load_file(ckpt)
image_proj_sd = {}
ip_sd = {}
for k in sd:
    if k.startswith("unet"):
        pass
    elif k.startswith("image_proj_model"):
        image_proj_sd[k.replace("image_proj_model.", "")] = sd[k]
    elif k.startswith("adapter_modules"):
        ip_sd[k.replace("adapter_modules.", "")] = sd[k]

torch.save({"image_proj": image_proj_sd, "ip_adapter": ip_sd}, f"{os.path.dirname(ckpt)}/ip-adapter_sdxl.bin")
```

I have replaced `torch.load` with safetensor's `load_file`, and this works for me.
