### ISSUE TITLE
Question about "a better way for ContrlNet "

### ISSUE THREAD

**Issue by fortunechen** [tencent-ailab/IP-Adapter#38]
Hi, authors. 

Thanks for the great open-sourcing work.

Could you please explain what is the actual computation for ContrlNet?

<img width="577" alt="image" src="https://github.com/tencent-ailab/IP-Adapter/assets/26025440/7252edb2-5b0b-4f04-a390-bda30a5bbd7a">

**Comment by xiaohu2015** [comment]
@fortunechen hi, we don't want that ControlNet receive image prompt as input. In our previous implementation, we modify the `forward` method to achieve this. But the new way is that we modify the attention processor of ControlNet (also work for sdxlcontrolnet pipe).
