### ISSUE TITLE
一些训练增强方式细节的请教~

### ISSUE THREAD

**Issue by xuyu666** [tencent-ailab/IP-Adapter#393]
作者您好：
很喜欢ipadapter这种简单实用的模型，于是想着在人脸数据之外的数据集上尝试。在训练的过程中，发现对ref_img的背景依赖比较严重，也可能数据集数量太少。我有看到您的wiki相关内容，链接在[这里](https://github.com/tencent-ailab/IP-Adapter/wiki/IP%E2%80%90Adapter%E2%80%90Face)。其中，您有提到对人脸做不同程度的裁剪，以及对ref_img实施水平翻转和颜色抖动。我有几点疑问想了解下：

1. 对人脸做不同尺度的裁剪指的是训练集中的GT图么，还是ref_img?
2. ref_img参与颜色抖动的系数是多少范围的，是否涉及颜色空间转换？
3. 能提供更多的训练时的数据增强方式建议么？谢谢！

![image](https://github.com/tencent-ailab/IP-Adapter/assets/49869475/ccf2d756-bb5b-438e-99ae-bb638ad00135)

祝好！

**Comment by xiaohu2015** [comment]
```
        self.face_transform = transforms.Compose([
            transforms.RandomResizedCrop(
                224, scale=(0.5, 1.0), ratio=(0.8, 1.2), interpolation=transforms.InterpolationMode.BICUBIC
                ),
            transforms.RandomHorizontalFlip(),
            transforms.RandomApply(
                [transforms.ColorJitter(brightness=0.4, contrast=0.4, saturation=0.2, hue=0.1)], p=0.8,
            ),
            transforms.RandomGrayscale(p=0.2),
            transforms.RandomApply([transforms.GaussianBlur(kernel_size=7)], p=0.2),
            transforms.RandomSolarize(threshold=128, p=0.2),
        ])
```

**Comment by xuyu666** [comment]
好的，谢谢哥

徐玉
***@***.***

签名由 网易灵犀办公 定制


Original:
From:Hu Ye< ***@***.***>Date:2024-07-02 12:11:54To:tencent-ailab/IP-Adapter< ***@***.***>Cc:xuyu666< ***@***.***>、Author< ***@***.***>Subject:Re: [tencent-ailab/IP-Adapter] 一些训练增强方式细节的请教~ (Issue #393)
        self.face_transform = transforms.Compose([
            transforms.RandomResizedCrop(
                224, scale=(0.5, 1.0), ratio=(0.8, 1.2), interpolation=transforms.InterpolationMode.BICUBIC
                ),
            transforms.RandomHorizontalFlip(),
            transforms.RandomApply(
                [transforms.ColorJitter(brightness=0.4, contrast=0.4, saturation=0.2, hue=0.1)], p=0.8,
            ),
            transforms.RandomGrayscale(p=0.2),
            transforms.RandomApply([transforms.GaussianBlur(kernel_size=7)], p=0.2),
            transforms.RandomSolarize(threshold=128, p=0.2),
        ])
