### ISSUE TITLE
Question on adding IP-Adapter on SD3

### ISSUE THREAD

**Issue by wendashi** [tencent-ailab/IP-Adapter#399]
Thanks for your awesome work❤️, and I notice that you released 'sd3_attention_processor.py' last week, so I am trying to use it on training IP-Adapter for SD3, but i meet some questions, hope you can provide some advice🙏

(1) Should I change every 'attn.processor' to 'IPJointAttnProcessor2_0()' in  'sd3_attention_processor.py' ?

In SD1.5 tutorial_train.py,  you changed `attn1.processor`  → `AttnProcessor()` cause attn1 is self-attention, while changed
`attn2.processor` → `IPAttnProcessor()` to add another layer of cross-attention, cause attn2 is cross-attention.

but attn_processors.keys of `SD3Transformer2DModel` like this, and every attn is the same joint attention(JointAttnProcessor2_0).

```
attn_processors.keys:, transformer_blocks.0.attn.processor
attn_processors.keys:, transformer_blocks.1.attn.processor
attn_processors.keys:, transformer_blocks.2.attn.processor
attn_processors.keys:, transformer_blocks.3.attn.processor...
```

(2)Dimension of inputs in IPJointAttnProcessor2_0

Also in SD1.5 tutorial_train.py,  IPAttnProcessor(hidden_size=`block_out_channels`, cross_attention_dim=`cross_attention_dim`) from the following Key_configs:

```
Key_config: block_out_channels, Value_config: [320, 640, 1280, 1280]
....
Key_config: cross_attention_dim, Value_config: 768

```

so is it same for IPJointAttnProcessor2_0 to define the input dim?  such as IPJointAttnProcessor2_0(context_dim=`joint_attention_dim`, hidden_dim=`out_channels`, ip_hidden_states = `out_channels`) from the following Key_configs:

```
Key_config: joint_attention_dim, Value_config: 4096
...
Key_config: out_channels, Value_config: 16

```

(3) Is `ip_hidden_states = hidden_states` ?

`ip_hidden_states` is a new input in the __call__() of IPJointAttnProcessor2_0(), I'm not very sure how to define this input.

**Comment by LeonNerd** [comment]
hi,I have the same problem, do you have any progress? thank you

**Comment by lh-13** [comment]
@wendashi @LeonNerd  how did you finally solve this problem?

**Comment by dongdk** [comment]
+1
