### ISSUE TITLE
Generating undersaturated images

### ISSUE THREAD

**Issue by SantiagoJN** [tencent-ailab/IP-Adapter#404]
Thank you for this amazing work. The documentation and paper are crystal clear, and they are incredibly useful.

I got a couple questions which I hope you can assist me with:

**Generating undersaturated images**: I've trained a model conditioned with images that come from a custom rendered dataset (I attach a couple samples of this dataset below), which seems to have properly learnt this distribution, but when trying to generate new samples with this setup (IP-Adapter XL with my images as image conditioning, and a controlnet depth), it seems like all the generated images are undersaturated (I also attach some examples of this below). Do you have any idea on why is this happening?

_Samples used to train IP-Adapter:_
![1_1_cambridge_2k sphere MERL_EDIT-beige-fabric_diff_mix_natural-209_spec_hue_1_sat_0_spec_0](https://github.com/user-attachments/assets/0a41b725-53bf-4674-9e5e-b7e7ac7afd14) ![1_1_cambridge_2k bunny_vt MERL_EDIT-beige-fabric_diff_mix_special-walnut-224_spec_hue_0_sat_0_spec_2](https://github.com/user-attachments/assets/8ba2d9dc-9ce2-4bcc-acbc-7a09c8c228ae) <undersaturated imgs> ![1_1_cambridge_2k surface2-1000x1000part RGL-chm_light_blue_rgb](https://github.com/user-attachments/assets/51239ceb-509a-4256-aa19-0b6fead3e083)

_Generated undersaturated images (controlnet conditioned with an image of a pumpkin):_
![Captura de pantalla 2024-07-17 140548](https://github.com/user-attachments/assets/0ab1139a-05f0-45ec-bb36-9076379cc050)

**Unable to multimodal conditioning with text prompt**: I've trained an IP-Adapter with a custom image embedder, and it kinda works when plugging a controlnet in the pipeline to condition with, for example, depth, but when using just my image encoder with text prompt, the model either uses one information or the other (depending on the `scale` factor). During the training of IP-Adapter, I've used just general sentences as text prompt (just like "best quality, high quality"), but as far as I know, the model should be able to use its prior knowledge to, for example, create an image of a bunny, together with the new image conditioning which I trained. Am I missing something? Should I follow some other strategy for training my model to achieve this multimodal conditioning?

**Comment by john09282922** [comment]
Can you tell me how to solve? did you train controlnet+ip-adapter?

**Comment by SantiagoJN** [comment]
> Can you tell me how to solve? did you train controlnet+ip-adapter?

I was training IP-Adapter alone, and it was mainly an issue of wrong normalization of the input
