### ISSUE TITLE
环境？

### ISSUE THREAD

**Issue by Qiuhao-Wu** [tencent-ailab/IP-Adapter#428]

**Comment by Qiuhao-Wu** [comment]
有没有requirements.txt

**Comment by Qiuhao-Wu** [comment]
如果需要一个个手动装  哪里报错 装哪个包  也太恶心了

**Comment by Qiuhao-Wu** [comment]
fix

**Comment by grrrute** [comment]
Hello, I have the same question. The authors do not appear to provide information on environmental dependencies. Just installing diffusers is not enough. Could you please tell me the complete requirements.txt ? @Qiuhao-Wu
