### ISSUE TITLE
Models .bin not showing on controlnet a1111

### ISSUE THREAD

**Issue by AIrtistry** [tencent-ailab/IP-Adapter#49]
Hi, I placed the models ip-adaptater_sd15.bin ,  ip-adapter-plus_sd15.bin and ip-adapter-plus-face_sd15.bin into ../stable-diffusion-webui > extensions > sd-webui-controlnet > models but when I restart a1111, they not showing into the model field of controlnet ( 1.1.4 )

Thanks

**Comment by xiaohu2015** [comment]
@AIrtistry you rename file suffix with .pth

**Comment by AIrtistry** [comment]
thanks its seems to work
