### ISSUE TITLE
Doubts regarding the model

### ISSUE THREAD

**Issue by debjit-bw** [tencent-ailab/IP-Adapter#50]
I'm just trying to understand how IP Adapter does these powerful manipulations.

So we are encoding the image into embeddings, combining them with the prompt's embeddings and then creating an image based on that. I see we are changing the unet, but I don't understand how.

I also ran into issues using embeddings directly instead of passing in the prompt as a string. Here are the 2 doubts in more detail:

## 1
What does this do:
```python
input_ids = pipe.tokenizer(prompt, return_tensors="pt").input_ids
```
I saw this in the `set_ip_adapter` function. Is this the one that's changing the vae decoder? What does this do, and am I incorrect in assessing this?

## 2
I changed some function inputs, in order to use prompt embeds directly, for example doing this:
```python
input_ids = pipe.tokenizer(prompt, return_tensors="pt").input_ids
for i in range(0, input_ids.shape[-1], max_length):
    concat_embeds.append(pipe.text_encoder(input_ids[:, i: i + max_length])[0])
prompt_embeds = torch.cat(concat_embeds, dim=1)
```
Tried inputting this, and commenting out the following in IP Adapter's `generate(...)` function.
```python
prompt_embeds = self.pipe._encode_prompt(...)
```
This however gave incorrect results in the output image. What am I doing wrong?

## 3 (Out of scope)
I know this is out of scope, but is there any way of also loading a LoRA model's weights in the model's pipeline? If I load a LoRA model using `pipe.load_lora_weights(...)` before calling ip_adapter, will it retain those weights?

## Thanks
I know these are many questions. Thanks a lot in advance!

## Edits:
Forgot to mention earlier, but this is some amazing work you guys did, I love the idea.

**Comment by xiaohu2015** [comment]
@debjit-bw thanks for your attention to our work, I think you can read our paper to get more information.

for your questions:

1) in the set_ip_adapter function, we don't have the code you mentioned.
2) I don't konw why you do these changes, it seems like you encoder text tokens individually?
3)

**Comment by debjit-bw** [comment]
1. I'm sorry I meant `unet.set_attn_processor(attn_procs)` this line
2. I want to use prompts larger than the 77 token limit, and if I do this normally then it ignores the tokens after a particular limit. That's why I'm doing this
3. You said `You can merge lora to a new model`, do you mean I can train a new model or I can merge it in the pipeline itself?

**Comment by xiaohu2015** [comment]
@debjit-bw
1) we modify the attention processor of unet to realize the decoupled cross-attention for image prompt.
2) if you want to use text prompts more than 77 token, you can refer to https://github.com/tencent-ailab/IP-Adapter/pull/39, or you can use webui or comfyui
3) I mean you can merge the lora into unet, and get a new unet model.

**Comment by debjit-bw** [comment]
@xiaohu2015 

1.  okay thanks, got it
2. ah alright. i asked the doubt in the pr you linked
3. oh yeah can do that, thanks again

i'm resolving this issue
