### ISSUE TITLE
adding noise to the uncond images

### ISSUE THREAD

**Issue by cubiq** [tencent-ailab/IP-Adapter#51]
have you experimented adding a little noise to the zeroed tensors?

I made a few tests with the Plus model and the results are... interesting. Basically instead of a zeroed embed I'm passing a random +/- 0.5 noise (or even higher).

This is a quick example, sometimes the result is quite better, you just need to keep it low otherwise it starts "burning" the image.

![noise example](https://i.imgur.com/Sns0NBj.jpg)

wondering if this makes any sense

**Comment by xiaohu2015** [comment]
@cubiq hi, I think this is reasonable, you can think of it as negative image prompt.
For the text-to-image models, we trained them with randomly dropping text (set text=""). In the inference stage, we can set uncond text = "", but in fact, we can use a non-empty string, which is negative prompt.
For the IP-Adapter, we trained it with randomly dropping image (set image to a zero). Hence, we also can use a non-zero image as uncond image in the text stage.

**Comment by cubiq** [comment]
I did what you suggested @xiaohu2015 basically sending a negative image instead of a "zero" one and it works as expected. It's pretty impressive.

In the picture below sending a black and white negative image you get a very saturated result, by sending a very saturated RGB image you get a very desaturated result.

Need to play a little more with it. The base model doesn't seem influenced by what image is actually inside the negative image but just by the colors/saturation/brightness.

![negative image](https://i.imgur.com/OvoCbr4.jpg)
