### ISSUE TITLE
A1111: scaled_dot_product_attention

### ISSUE THREAD

**Issue by wade-wws** [tencent-ailab/IP-Adapter#52]
getting the issue of AttributeError: module 'torch.nn.functional' has no attribute 'scaled_dot_product_attention'
I have the latest torch, controlnet 1.1.409, renamed to .pth,
everything looks good just erroring out. 

seeing if anyone else has this issue

**Comment by xiaohu2015** [comment]
@wade-wws you can update the torch to 2.0 version.

**Comment by wade-wws** [comment]
I am at 2.0.1

**Comment by wade-wws** [comment]
apparently I had 2.01 on my system but not for a111.

Open CMD or Terminal inside your stable-diffusion-webui folder then type

```
cd venv/Scripts
activate
pip install --force-reinstall torch torchvision --index-url https://download.pytorch.org/whl/cu118
pip install --force-reinstall --no-deps --pre xformers
```

thx

**Comment by Flerndip** [comment]
There seems no way to do this fix with the windows 1-click installer's format.  There is no stable-diffusion-webui folder and thus no venv/Scripts folder.
