### ISSUE TITLE
About foreground segmentation

### ISSUE THREAD

**Issue by lxd941213** [tencent-ailab/IP-Adapter#55]
Hello, I have a question. During inference, the foreground objects need to be picked out using instance segmentation. Is this necessary during training? Also, what is the specific segmentation method used in the paper? Looking forward to your reply, thank you.

**Comment by xiaohu2015** [comment]
@lxd941213 in the training stage, we don't segment the objects. Hence, you don't need to do that. But if you want to create good images, you can the foreground objects. In the future, we plan to train a IP-Adapter with foreground objects as image condition.

**Comment by lxd941213** [comment]
> Can you tell me what specific segmentation model you use?

**Comment by xiaohu2015** [comment]
> > Can you tell me what specific segmentation model you use?

I think we can use some matting model? We have't made a try.

**Comment by lxd941213** [comment]
> > > Can you tell me what specific segmentation model you use?
> 
> I think we can use some matting models? We have't made a try.

Do you mean that you did not perform foreground extraction during inference?

**Comment by xiaohu2015** [comment]
> > > > Can you tell me what specific segmentation model you use?
> > 
> > 
> > I think we can use some matting models? We have't made a try.
> 
> Do you mean that you did not perform foreground extraction during inference?

in the training and inference stage, we don't do that.

**Comment by lxd941213** [comment]
> > > > > Can you tell me what specific segmentation model you use?
> > > 
> > > 
> > > I think we can use some matting models? We have't made a try.
> > 
> > 
> > Do you mean that you did not perform foreground extraction during inference?
> 
> in the training and inference stage, we don't do that.

OK, thank you for your reply.

**Comment by renrenzsbbb** [comment]
Thanks for your greak work and open-source code. have you try on foreground objects? I find that paper "DreamTuner: Single Image is Enough for Subject-Driven Generation" experiment it with foreground object and depth control.
