### ISSUE TITLE
invalid load key, '<'.  [ip adapter plus face demo]

### ISSUE THREAD

**Issue by h3clikejava** [tencent-ailab/IP-Adapter#60]
https://colab.research.google.com/drive/1_Vtos4PRqZWAg69sC9XuSBBt6Mw_aDCz?usp=sharing

ip_model = IPAdapterPlus(pipe, image_encoder_path, ip_ckpt, device, num_tokens=16)

---------------------------------------------------------------------------
UnpicklingError                           Traceback (most recent call last)
[<ipython-input-7-99bd5220eb14>](https://localhost:8080/#) in <cell line: 1>()
----> 1 ip_model = IPAdapterPlus(pipe, image_encoder_path, ip_ckpt, device, num_tokens=16)

3 frames
[/usr/local/lib/python3.10/dist-packages/torch/serialization.py](https://localhost:8080/#) in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
   1031             "functionality.")
   1032 
-> 1033     magic_number = pickle_module.load(f, **pickle_load_args)
   1034     if magic_number != MAGIC_NUMBER:
   1035         raise RuntimeError("Invalid magic number; corrupt file?")

UnpicklingError: invalid load key, '<'.

**Comment by xiaohu2015** [comment]
@h3clikejava you should use 
```
!wget -O /content/IP-Adapter/models/ip-adapter-plus-face_sd15.bin https://huggingface.co/h94/IP-Adapter/resolve/main/models/ip-adapter-plus-face_sd15.bin
```
not 
```
!wget -O /content/IP-Adapter/models/ip-adapter-plus-face_sd15.bin https://huggingface.co/h94/IP-Adapter/blob/main/models/ip-adapter-plus-face_sd15.bin
```
