### ISSUE TITLE
Some Implemention Details Discussion

### ISSUE THREAD

**Issue by zcai0612** [tencent-ailab/IP-Adapter#61]
Hi, Dear Authors.

After reading the code, I found that you let the image features after projection (concept features) put into the Adapter layers. 

However, in some relevant works (personally), eg. InstantBooth (https://arxiv.org/abs/2304.03411), Subject Diffusion (https://arxiv.org/abs/2307.11410), they inject the image token features (patch features) to the adapter layers in the UNet of SD (they use self-attn). 
It seems like patch features may contain more detailed features so that the model can preserve the characteristics of input images better. 

Concept features seem to have more high-level semantic info. Maybe this change can help IP-Adapter be more flexible but to some extent lose some abilities of subject/identity-driven generation abilities.

It is just my personal opinion, talks are welcome.

**Comment by xiaohu2015** [comment]
@zcai0612 we also trained a IP-Adapter with patch features, you can refer to `4.4 Ablation Study` of the paper

**Comment by zcai0612** [comment]
> @zcai0612 we also trained a IP-Adapter with patch features, you can refer to `4.4 Ablation Study` of the paper

Thanks for your response, It seems that we share similar ideas according to the paper, sorry for my carelessness.  
Do you mind releasing the code and model with patch features? Maybe some analysis and summary works can be conducted on it.

**Comment by xiaohu2015** [comment]
@zcai0612 hi, the code and model have been released

**Comment by zcai0612** [comment]
> @zcai0612 hi, the code and model have been released

Thanks a lot！
