### ISSUE TITLE
why the size of the model I trained is much larger than pretrained model?

### ISSUE THREAD

**Issue by ruaruaruabick** [tencent-ailab/IP-Adapter#63]
I trained with the deepspeed 2 Zero, after I run zero_to_fp32.py, the size of "pytorch_model.bin" generated is ~1.7G, but the pretrained model "ip-adapter_sd15.bin" is only ~43M

**Comment by xiaohu2015** [comment]
@ruaruaruabick because the unet has also been saved, but in fact, it don't train. You can get the weights of IP-Adapter from the chekpont: https://github.com/tencent-ailab/IP-Adapter/issues/17#issuecomment-1696961596

**Comment by ruaruaruabick** [comment]
> @ruaruaruabick because the unet has also been saved, but in fact, it don't train. You can get the weights of IP-Adapter from the chekpont: [#17 (comment)](https://github.com/tencent-ailab/IP-Adapter/issues/17#issuecomment-1696961596)

thanks a lot
