### ISSUE TITLE
About Fine-grained Features

### ISSUE THREAD

**Issue by lxd941213** [tencent-ailab/IP-Adapter#64]
Sorry to bother you again, but I really love your work. I saw from the paper that you extracted the grid features of the penultimate layer from the CLIP image encoder. Why did you choose the penultimate layer instead of the last layer? In addition, can the number of tokens be greater than 4?

**Comment by xiaohu2015** [comment]
@lxd941213 hi, sd2.1 and sdxl both use the penultimate layer of text encoder. Hence, we also use the grid features of the penultimate layer from the CLIP image encoder, but I think using last layer also works. The number of tokens we used is 16, you can use a greater number.

**Comment by lxd941213** [comment]
> @lxd941213 hi, sd2.1 and sdxl both use the penultimate layer of text encoder. Hence, we also use the grid features of the penultimate layer from the CLIP image encoder, but I think using last layer also works. The number of tokens we used is 16, you can use a greater number.

Thanks for your answer
