### ISSUE TITLE
Error when running IPAdapterXL notebook locally

### ISSUE THREAD

**Issue by levi** [tencent-ailab/IP-Adapter#66]
When loading the IPAdapter models locally using the notebook in this repo, I get the following error:

```
  File "ip_adapter/ip_adapter.py", line 53, in __init__
    self.load_ip_adapter()
  File "ip_adapter/ip_adapter.py", line 91, in load_ip_adapter
    self.image_proj_model.load_state_dict(state_dict["image_proj"])
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ImageProjModel:
        size mismatch for proj.weight: copying a param with shape torch.Size([8192, 1024]) from checkpoint, the shape in current model is torch.Size([8192, 1280]).
```

This is what my setup looks like:

```
image_encoder_path = "/root/ip_adapter/sdxl_models/image_encoder"
ip_ckpt = "/root/ip_adapter/sdxl_models/ip-adapter_sdxl_vit-h.bin"
device = "cuda"
pipe = IPAdapterXL(
    self.pipe, image_encoder_path, ip_ckpt, device
)
```

I am using the models fetched from the huggingface repo.

**Comment by levi** [comment]
Looks like a specific loading error with `ip-adapter_sdxl_vit-h.bin`. Switching to `ip-adapter_sdxl.bin` works fine.

What do I need to do to try the other model?

**Comment by xiaohu2015** [comment]
> Looks like a specific loading error with `ip-adapter_sdxl_vit-h.bin`. Switching to `ip-adapter_sdxl.bin` works fine.
> 
> What do I need to do to try the other model?

hi, as discussed in https://github.com/tencent-ailab/IP-Adapter#sdxl_10, you should use the `models/image_encoder` for `ip-adapter_sdxl_vit-h.bin`

**Comment by levi** [comment]
I’ll debug this some more, but that combo isn’t working for me. Does it need to load the safetensors image encoder, specifically?

**Comment by xiaohu2015** [comment]
> I’ll debug this some more, but that combo isn’t working for me. Does it need to load the safetensors image encoder, specifically?

since `ip-adapter_sdxl_vit-h.bin` is trained with CLIP-ViT-H, you should use this image encoder: https://huggingface.co/h94/IP-Adapter/tree/main/models/image_encoder

**Comment by levi** [comment]
Great, thanks
