### ISSUE TITLE
How many face images used to train the face-ip-adaptor?

### ISSUE THREAD

**Issue by fortunechen** [tencent-ailab/IP-Adapter#74]
Hi, authors

The face-ip-adaptor works relatively well.

I wonder how many face images used to train the face-ip-adaptor?

Thx

**Comment by xiaohu2015** [comment]
@fortunechen we use about 40w images containing people

**Comment by fortunechen** [comment]
Is the face encoder trained from scratch or from common encoder trained from 10M common images?

**Comment by xiaohu2015** [comment]
@fortunechen hi, in current version, we use openclip ViT-H as image encoder

**Comment by fortunechen** [comment]
is the resampler only trained on 40w images ? Maybe it can be resumed from previous ckpt trained on 10M common images(according to the paper), then trained on 40w images

**Comment by xiaohu2015** [comment]
@fortunechen no, we don't use the previous ckpt, but maybe we can try it.

**Comment by xiaohu2015** [comment]
> > @fortunechen we use about 40w images containing people
> 
> Does this mean 40,000 or 400,000?

400,000

**Comment by lxd941213** [comment]
Does this face dataset only include faces? Does it also include the upper body?

**Comment by xiaohu2015** [comment]
@lxd941213 For better generalization, we do not specially deal with the person image. In other words, the dataset contains a wide variety of person images. Maybe we only crop a part of body, we can achive more better results.

**Comment by lxd941213** [comment]
> 为了更好地概括，我们不专门处理人物形象。换句话说，数据集包含各种各样的人物图像。也许我们只裁剪身体的一部分，我们可以取得更好的效果。

How to deal with the caption corresponding to the image? The caption should also include content that has nothing to do with faces, right? For example, there will be descriptors such as environment.

**Comment by lxd941213** [comment]
> @lxd941213 For better generalization, we do not specially deal with the person image. In other words, the dataset contains a wide variety of person images. Maybe we only crop a part of body, we can achive more better results.

How to deal with the caption corresponding to the image? The caption should also include content that has nothing to do with faces, right? For example, there will be descriptors such as environment.

**Comment by xiaohu2015** [comment]
@lxd941213 we just use the original caption. Because image condition tend to be stronger than text condition, so this is not a problem.

**Comment by lxd941213** [comment]
@xiaohu2015  thank you

**Comment by nationalflag** [comment]
40w images in LAION-2B and COYO-700M?

**Comment by xiaohu2015** [comment]
> 40w images in LAION-2B and COYO-700M?

yeah
