### ISSUE TITLE
I couldn't find the file ip-adapter-plus_sd15.bin in the model I trained myself.

### ISSUE THREAD

**Issue by chenjingcheng** [tencent-ailab/IP-Adapter#79]
Hello, thank you very much for your work. I have used your code to train on my data. However, when I saved the model, it included all the data, and I didn't get the smaller 44MB file like the one you mentioned: ip-adapter-plus_sd15.bin. How can I obtain this file? Thank you.

**Comment by chenjingcheng** [comment]
add more info:

ls output_dir/checkpoint-45000/ -lh
total 3.8G
-rw-rw-r-- 1 aifont aifont 375M Sep 19 14:23 optimizer.bin
-rw-rw-r-- 1 aifont aifont 3.4G Sep 19 14:23 pytorch_model.bin
-rw-rw-r-- 1 aifont aifont  15K Sep 19 14:23 random_states_0.pkl
-rw-rw-r-- 1 aifont aifont  557 Sep 19 14:23 scaler.pt

**Comment by xiaohu2015** [comment]
@chenjingcheng you can refer to https://github.com/tencent-ailab/IP-Adapter/issues/17#issuecomment-1696961596

**Comment by chenjingcheng** [comment]
> @chenjingcheng you can refer to [#17 (comment)](https://github.com/tencent-ailab/IP-Adapter/issues/17#issuecomment-1696961596)

thank you very much!
