### ISSUE TITLE
Regarding text guidance and image guidance

### ISSUE THREAD

**Issue by Hzj199** [tencent-ailab/IP-Adapter#81]
Based on IPAdapter, I replaced the image_encoder with the text encoder from the Chinese CLIP, and trained it with tens of millions of data, but it couldn't generate images. Is image guidance easier compared to text guidance?

**Comment by xiaohu2015** [comment]
@Hzj199 Since images contain more information than text, image guidance is easier compared to text guidance. If you use chinese CLIP text encoder, I think you use a higer drop rate for original text encoder.

**Comment by Hzj199** [comment]
What does `drop rate` refer to? Is it similar to `text_encoder( text_input_ids, output_hidden_states=True ).hidden_states[-2]`? Or is it the dropout rate?

**Comment by xiaohu2015** [comment]
@Hzj199 https://github.com/tencent-ailab/IP-Adapter/blob/main/tutorial_train.py#L67

**Comment by Hzj199** [comment]
@xiaohu2015 During the training process, the input of the original text encoder is always set to empty, just like 'Bridge Diffusion Model: bridging non-English language-native text-to-image diffusion model with English communities'.

**Comment by xiaohu2015** [comment]
@Hzj199 I think there may be something wrong with your training. Although the text condition is more difficult to train than the image condition, it is not impossible to generate images.

**Comment by Hzj199** [comment]
@xiaohu2015 Thank you for your explanation. I'll check the code and continue with the training.
