### ISSUE TITLE
`OutOfMemoryError` VRAM requirements 

### ISSUE THREAD

**Issue by 5shekel** [tencent-ailab/IP-Adapter#82]
hi, i tried to run `IP-Adapter/ip_adapter_sdxl_controlnet_demo.ipynb` on a
 * 3060/12Gb 
 * T4/16Gb. 
```
# load ip-adapter
ip_model = IPAdapterXL(pipe, image_encoder_path, ip_ckpt, device)
```
an in both i get `CUDA out of memory`, here is the T4
```
OutOfMemoryError: CUDA out of memory. Tried to allocate 44.00 MiB (GPU 0; 14.58 GiB total capacity; 13.86 GiB already allocated; 19.31 MiB free; 14.44 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

```

**Comment by 5shekel** [comment]
L4 with 24Gb , the same.
`OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 21.99 GiB total capacity; 21.09 GiB already allocated; 15.69 MiB free; 21.79 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

**Comment by thhung** [comment]
@5shekel Did you manage to solve the problem? With 15GB, I have an OOM, too.
