### ISSUE TITLE
how to set image height and width ?

### ISSUE THREAD

**Issue by PansaLegrand** [tencent-ailab/IP-Adapter#84]
I pass the height and width for generation, but the result is quite bizarre.

```
import torch
from diffusers import StableDiffusionPipeline, StableDiffusionImg2ImgPipeline, StableDiffusionInpaintPipelineLegacy, DDIMScheduler, AutoencoderKL
from PIL import Image
base_model_path = "SG161222/Realistic_Vision_V4.0_noVAE"
vae_model_path = "stabilityai/sd-vae-ft-mse"
image_encoder_path = "IP-Adapter/models/image_encoder"
ip_ckpt = "IP-Adapter/models/ip-adapter-plus_sd15.bin"
device = "cuda"
noise_scheduler = DDIMScheduler(
    num_train_timesteps=1000,
    beta_start=0.00085,
    beta_end=0.012,
    beta_schedule="scaled_linear",
    clip_sample=False,
    set_alpha_to_one=False,
    steps_offset=1,
)
vae = AutoencoderKL.from_pretrained(vae_model_path).to(dtype=torch.float16)
pipe = StableDiffusionPipeline.from_pretrained(
    base_model_path,
    torch_dtype=torch.float16,
    scheduler=noise_scheduler,
    vae=vae,
    feature_extractor=None,
    safety_checker=None
)
from ip_adapter import IPAdapterPlus
image = Image.open("boy.png")
image.resize((512, 512)) # is this necessary
print(image.size)

ip_model = IPAdapterPlus(pipe, image_encoder_path, ip_ckpt, device, num_tokens=16)
only image prompt
images = ip_model.generate(pil_image=image, num_samples=1, num_inference_steps=10, seed=42,
                           height = 1024, width = 1024)
images[0]
```
The input image
![boy](https://github.com/tencent-ailab/IP-Adapter/assets/119485913/4ba04a9d-d0f1-4240-888c-ee4e5363efdd)

The generated image
![boy0](https://github.com/tencent-ailab/IP-Adapter/assets/119485913/cce28559-e031-4aef-89e3-6a00cfe09b4c)

It seems that the input image is duplicated.
My questions are : 
1. is it necessary to resize the input image ?
2. what's the optimal height and width for generation ? It seems that 512 * 512 is the only one stable.

**Comment by PansaLegrand** [comment]
try with object image of (1600, 1600)
![jucer](https://github.com/tencent-ailab/IP-Adapter/assets/119485913/0b8ff82f-9ddd-4b4c-95ae-6bc2eb43d1a5)

generation height set to 512, and width 1024

![下载](https://github.com/tencent-ailab/IP-Adapter/assets/119485913/002ccfab-c6fc-481d-97f4-bd84c0f9b664)

**Comment by xiaohu2015** [comment]
@PansaLegrand since the ip-adapter is trained with 512x512, generation with 512x512 is stable. If you want to generate higher resolution images, you can firstly generate 512x512 images and then use Hires. fix (image to image).

**Comment by PansaLegrand** [comment]
> @PansaLegrand since the ip-adapter is trained with 512x512, generation with 512x512 is stable. If you want to generate higher resolution images, you can firstly generate 512x512 images and then use Hires. fix (image to image).

Thank you for the reply. I will stick to 512 * 512 then.
