### ISSUE TITLE
IPAdapter with FreeU?

### ISSUE THREAD

**Issue by jadechip** [tencent-ailab/IP-Adapter#86]
Has anyone been able to use IPAdapter with FreeU? I tried but the resemblance of the subject gets messed up :/ 
Without FreeU:
<img width="411" alt="image" src="https://github.com/tencent-ailab/IP-Adapter/assets/5690384/3308cfb6-959b-4541-be02-2d826c925506">
With FreeU:
<img width="414" alt="image" src="https://github.com/tencent-ailab/IP-Adapter/assets/5690384/16fed983-f509-472b-9de3-f3215987d1ea">

**Comment by xiaohu2015** [comment]
@jadechip hi, we don't test that, can you give more information?
