### ISSUE TITLE
Training weight file issue.

### ISSUE THREAD

**Issue by xuliangdong1999** [tencent-ailab/IP-Adapter#89]
Using your training code to train, the resulting weight file is 3.5GB, but the weight file provided by you is only 45MB. How can this issue be resolved? Additionally, after printing the weight file information, it appears that the necessary keys for 'load_ip_adapter', namely 'iamge_proj' and 'ip_adapter', are missing. Can you please explain this situation?

**Comment by xiaohu2015** [comment]
@xuliangdong1999 you can refer to this https://github.com/tencent-ailab/IP-Adapter/issues/17#issuecomment-1696961596

**Comment by xuliangdong1999** [comment]
Thanks！
