### ISSUE TITLE
Question about the weight of VAE

### ISSUE THREAD

**Issue by CHNxindong** [tencent-ailab/IP-Adapter#93]
Thanks for the great work. I have a question about the weight of VAE. The weight of VAE in the IP-Adapter is:
![image](https://github.com/tencent-ailab/IP-Adapter/assets/20262070/b30780cc-f7cd-4955-8e1a-3a33722c2ecf)

But the weight of VAE in many works such as Tune-A-Video, Vid2vid-zero is:
![image](https://github.com/tencent-ailab/IP-Adapter/assets/20262070/81dc6142-29d9-4e05-abb8-ba67f411e03e)
![image](https://github.com/tencent-ailab/IP-Adapter/assets/20262070/1affbde5-53be-4e1c-beca-e2cb93b0441e)
Is there any difference in precise between them?

**Comment by xiaohu2015** [comment]
@CHNxindong hi, VAE don't affect the performance. Here, we use a better VAE to reduce some visual imperfections

https://huggingface.co/stabilityai/sd-vae-ft-mse-original has a higher reconstruction error

**Comment by CHNxindong** [comment]
I see. Thanks for the quick reply!
