### ISSUE TITLE
About training with xformers

### ISSUE THREAD

**Issue by KevinChen880723** [tencent-ailab/IP-Adapter#97]
Dear authors,

Thank you for your excellent work and for open-sourcing it, I did learn a lot from your work. Currently, I am working on running the code with Xformer, but I've encountered an issue. It seems that after using unet.enable_xformers_memory_efficient_attention(), the unet.set_attn_processor(attn_procs) function doesn't work.

Could you please provide me with some guidance on how to resolve this issue? I appreciate your help, and I wish you a great day!

Sincerely,
Kevin

**Comment by xiaohu2015** [comment]
@KevinChen880723 you can just refer to https://github.com/huggingface/diffusers/blob/07b297e7dec3f475a880c15addcb6c02c0690992/src/diffusers/models/attention_processor.py#L886

**Comment by KevinChen880723** [comment]
@xiaohu2015 Thank you for the quick response! Wish you a nice day :)

**Comment by JWargrave** [comment]
> @xiaohu2015 Thank you for the quick response! Wish you a nice day :)

I got the same problem, did you fix? Can you share the code to implement IPAdapterAttnProcessor2_0 using xformers? many thanks!
